# Default values for genesis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/basedmoney/based-loans
  tag: main
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
name: based-loans-ui

service:
  name: based-loans-ui
  type: NodePort
  port: 80
  protocol: TCP
  targetPort: 80

ingress:
  host: based.loans
  secret: based.loans-tls
  path: /

environment: []


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 3
  #   memory: 6Gi
  # requests:
  #   cpu: 2
  #   memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

secretMounts: []
